export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  ACCOUNTANT = 'ACCOUNTANT',
  STOREKEEPER = 'STOREKEEPER',
  DISPATCHER = 'DISPATCHER',
  TECHNICIAN = 'TECHNICIAN',
  CUSTOMER = 'CUSTOMER',
}

export enum JobStatus {
  PENDING = 'PENDING',
  ASSIGNED = 'ASSIGNED',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVED = 'ARRIVED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum Priority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  EMERGENCY = 'EMERGENCY',
}

export enum ServiceType {
  ELECTRICAL = 'ELECTRICAL',
  PLUMBING = 'PLUMBING',
  HVAC = 'HVAC',
  MANPOWER = 'MANPOWER',
  EQUIPMENT_RENTAL = 'EQUIPMENT_RENTAL',
  MATERIAL_SALES = 'MATERIAL_SALES',
}

export enum EquipmentStatus {
  AVAILABLE = 'AVAILABLE',
  RENTED = 'RENTED',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  RETIRED = 'RETIRED',
}

export enum ManpowerTrade {
  ELECTRICIAN = 'ELECTRICIAN',
  PLUMBER = 'PLUMBER',
  HVAC_TECHNICIAN = 'HVAC_TECHNICIAN',
  PIPE_FITTER = 'PIPE_FITTER',
  GENERAL_HELPER = 'GENERAL_HELPER',
  MASON = 'MASON',
}

export enum ManpowerStatus {
  AVAILABLE = 'AVAILABLE',
  DEPLOYED = 'DEPLOYED',
  ON_LEAVE = 'ON_LEAVE',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
  STRIPE_CARD = 'STRIPE_CARD',
  MOCK_CARD = 'MOCK_CARD',
  APPLE_PAY = 'APPLE_PAY',
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
  BANK_TRANSFER = 'BANK_TRANSFER',
}

export enum StockMovementType {
  PURCHASE_RECEIPT = 'PURCHASE_RECEIPT',
  VAN_TRANSFER = 'VAN_TRANSFER',
  JOB_CONSUMPTION = 'JOB_CONSUMPTION',
  DIRECT_SALE = 'DIRECT_SALE',
  ADJUSTMENT = 'ADJUSTMENT',
}
